# Reviewing some basic python commands and tricks

Ref: DataCamp

### lambda functions

In [3]:
echo_word = (lambda word1, echo: word1 * echo)

In [4]:
echo_word('hey', 5)

'heyheyheyheyhey'

Using lambda functions with map

In [5]:
spells = ["protego", "accio", "expecto patronum", "legilimens"]

In [9]:
shout_spells = map((lambda item: item + '!!!'), spells)

In [10]:
shout_spells

['protego!!!', 'accio!!!', 'expecto patronum!!!', 'legilimens!!!']

In [11]:
shout_spells_list = list(shout_spells)

In [12]:
print shout_spells_list

['protego!!!', 'accio!!!', 'expecto patronum!!!', 'legilimens!!!']


Using lambda function with filter

In [13]:
fellowship = ['frodo', 'samwise', 'merry', 'aragorn', 'legolas', 'boromir', 'gimli']

In [16]:
result = filter(lambda item: len(item) > 6, fellowship)

In [17]:
result

['samwise', 'aragorn', 'legolas', 'boromir']

Using lambda with reduce()

unlike map() and filter(), reduce() returns a single value as a result

In [18]:
stark = ['robb', 'sansa', 'arya', 'eddard', 'jon']

In [19]:
reduce(lambda item1, item2: item1 + item2, stark )

'robbsansaaryaeddardjon'

An alternate way of doing the above is as follows

In [22]:
def gibberish( *args):
    """Concatenate the strings in the args together"""
    join = ''
    for word in args:
        join += word
    return join    

In [24]:
type(stark)

list

In [26]:
gibberish('robb', 'sansa', 'arya', 'eddard', 'jon')

'robbsansaaryaeddardjon'

** Error messages **

In [27]:
len(34)

TypeError: object of type 'int' has no len()

len() works on strings, lists, and tuples, but not int type ones

In [28]:
# Define shout_echo
def shout_echo(word1, echo=1):
    """Concatenate echo copies of word1 and three
    exclamation marks at the end of the string."""

    # Initialize empty strings: echo_word, shout_words
    echo_word = ''
    shout_words = ''

    # Add exception handling with try-except
    try:
        # Concatenate echo copies of word1 using *: echo_word
        echo_word = word1 * echo

        # Concatenate '!!!' to echo_word: shout_words
        shout_words = echo_word + '!!!'
    except:
        # Print error message
        print("word1 must be a string and echo must be an integer.")

    # Return shout_words
    return shout_words

# Call shout_echo
shout_echo("particle", echo="accelerator")

word1 must be a string and echo must be an integer.


''

We can raise our own custom errors using the raise keyword

In [34]:
# Define shout_echo
def shout_echo(word1, echo=1):
    """Concatenate echo copies of word1 and three
    exclamation marks at the end of the string."""

    # Raise an error with raise
    if echo < 0:
        raise ValueError('echo must be greater than 0')

    # Concatenate echo copies of word1 using *: echo_word
    echo_word = word1 * echo

    # Concatenate '!!!' to echo_word: shout_word
    shout_word = echo_word + '!!!'

    # Return shout_word
    return shout_word

# Call shout_echo
shout_echo("particle", echo = -5)


ValueError: echo must be greater than 0

In [35]:
x = 'vsvgasv'

In [38]:
x[0:2]

'vs'

In [39]:
True + False

1

In [40]:
x = [1, 2, 3, 4]

In [41]:
type(x)

list

In [42]:
xx = [['a', 1], 2, 3]

In [43]:
type(xx)

list

** Lists **

In [44]:
x = ["a", "b", "c", "d"]
del(x[2])
x

['a', 'b', 'd']

In [45]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

Suppose we want to remove the str "poolhouse" and the corresponding area. Convince yourself that out of the following, there is only one correct way of doing it.

1) del(areas[10]); del(areas[11])

2) del(areas[10:11])

3) del(areas[-4:-2]) [correct one]

4) del(areas[-3]); del(areas[-4])

This is because as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change.

The ; sign is used to place commands on the same line.

** Copying a list **

In [47]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [48]:
areas_copy = areas
areas_copy[1] = 111
areas

[11.25, 111, 20.0, 10.75, 9.5]

In [49]:
areas_copy1 = areas[:]
areas_copy1

[11.25, 111, 20.0, 10.75, 9.5]

In [50]:
areas_copy1[0] = 22.2

In [51]:
areas

[11.25, 111, 20.0, 10.75, 9.5]

In [52]:
areas_copy2 = list(areas)
areas_copy2[3] = 33.3

In [55]:
areas_copy2, areas

([11.25, 111, 20.0, 33.3, 9.5], [11.25, 111, 20.0, 10.75, 9.5])

In [56]:
int(True)

1

In [57]:
int(False)

0

In [58]:
float(True)

1.0

In [59]:
str(True)

'True'

In [67]:
x = [1, 2, 1, 1, 4]

In [68]:
x.count(1)

3

In [69]:
x.index(4)

4

In [70]:
x.append(5)

In [71]:
x

[1, 2, 1, 1, 4, 5]

In [72]:
x.reverse()

In [75]:
x

[5, 4, 1, 1, 2, 1]

In [80]:
import numpy as np

In [81]:
x_np = np.array(x)

In [82]:
x_np

array([5, 4, 1, 1, 2, 1])

In [85]:
x_np > 1

array([ True,  True, False, False,  True, False], dtype=bool)

In [84]:
x_np[x_np >1]

array([5, 4, 2])

In [88]:
y_np = np.array([1, 2, 3, '4'])
y_np

array(['1', '2', '3', '4'],
      dtype='|S21')

type coercion in action

In [1]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

In [6]:
europe['italy'] = 2

In [7]:
europe

{'france': 'paris',
 'germany': 'berlin',
 'italy': 2,
 'norway': 'oslo',
 'spain': 'madrid'}

In [8]:
print europe

{'norway': 'oslo', 'italy': 2, 'germany': 'berlin', 'spain': 'madrid', 'france': 'paris'}


Note that the dictionaries are inherently unordered. Do not pay much attention to their order

In [15]:
'germany' in europe

True

In [16]:
'Germany' in europe

False

A way to find out if the key is in the dictionary

In [18]:
numberkeyvalue = {1:11, 2:22}

In [19]:
numberkeyvalue[1]

11

In [20]:
type(numberkeyvalue)

dict

In [21]:
type(numberkeyvalue[1])

int

Comparing strings

In [27]:
'sam' < 'yditi'

True

In [30]:
'sam' < 'Yditi'

False

In [38]:
'Sam' < 'sam'

True

In [39]:
'Sam' < 'am'

True

In [33]:
'Sam' < 'aditi'

True

According to the alphabet, s comes before y. 

Looks like the order is ABC..Z folowed by abc..z

In [40]:
3 < 4.1

True

In [41]:
3 < '1'

True

In [42]:
3 < '2r2'

True

In [44]:
True == 2

False

Boolean operators with numpy

In [46]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [47]:
np.logical_or(my_house > 18.5, my_house < 10)

array([False,  True, False,  True], dtype=bool)

my_house > 18.5 and my_house < 10 doesn't work with arrays

np.logical_and, np.logical_or, np.logical_not can be used in pandas dataframe for filtering values as well.

## Hacker statistics 

The problem is as follows:

Walking up the empire state building and play a game with the friend.

For 100 times you throw a dice, if it is 1 or 2, you go one step down. 
If it 3,4, or 5 you go one step up. If it is six, throw the dice again and walk resulting number of dice step up. Of course can't go below step number 0 and there is a 0.1% chance of falling down and going to 0. Say you start at step 50. You bet that in 100 moves you will reach 60 steps. What is the chance that you will win this bet? 

In [51]:
np.random.seed(123)

In [52]:
np.random.rand()

0.6964691855978616

In [53]:
np.random.rand()

0.28613933495037946

In [54]:
np.random.randint(1,7)

5

In [71]:
np.random.randint(1,7)

1

In [73]:
dice = np.random.randint(1,7)

step = 50

# Finish the control construct
if dice <= 2:
    step = step - 1
elif dice <= 5:
    step = step + 1
else:
    step = step + np.random.randint(1,7)

# Print out dice and step
print(dice)
print(step)

5
51
